import openstudio
import tempfile
import os
import shutil
import logging
from pathlib import Path
from typing import Dict, Any
from importlib.resources import files

from openstudio_toolkit.utils.measure_runner import MeasureRunner

# Configure logger
logger = logging.getLogger(__name__)

def _get_measure_dir() -> Path:
    """
    Get the view_model measure directory path using internal package resources.

    Returns:
    - Path: Absolute path to the view_model measure directory.
    """
    return Path(str(files('openstudio_toolkit.resources.measures').joinpath('view_model')))

def validator(osm_model: openstudio.model.Model) -> Dict[str, Any]:
    """
    Validate that the view_model measure resource exists and is properly structured.

    Parameters:
    - osm_model (openstudio.model.Model): The OpenStudio Model object.

    Returns:
    - Dict[str, Any]: Status dictionary with 'status' ('READY' or 'ERROR') and 'messages'.
    """
    messages = []

    # Check if measure resource exists
    try:
        measure_dir = _get_measure_dir()
        if not measure_dir.exists():
            msg = "ERROR: Measure resource 'view_model' not found."
            logger.error(msg)
            return {"status": "ERROR", "messages": [msg]}
    except Exception as e:
        msg = f"ERROR: Could not locate measure resource: {e}"
        logger.error(msg)
        return {"status": "ERROR", "messages": [msg]}

    runner = MeasureRunner()
    if not runner.verify_measure_content(str(measure_dir)):
        msg = "ERROR: Measure resource is invalid (missing measure.xml)."
        logger.error(msg)
        return {"status": "ERROR", "messages": [msg]}

    logger.info("view_model measure validation successful.")
    return {"status": "READY", "messages": ["OK: All validations passed."]}

def run(osm_model: openstudio.model.Model, output_path: str) -> str:
    """
    Execute the view_model measure to generate an interactive HTML model visualization.

    IMPORTANT: This task returns the path to the generated HTML file.

    Parameters:
    - osm_model (openstudio.model.Model): The OpenStudio Model object.
    - output_path (str): File path where the resulting HTML report will be saved.

    Returns:
    - str: The absolute path to the generated HTML report.

    Raises:
    - RuntimeError: If measure execution or resource handling fails.
    """
    logger.info("Starting View Model HTML generation task...")

    # Validate resource
    validation = validator(osm_model)
    if validation["status"] != "READY":
        raise RuntimeError(f"Validation failed: {validation['messages']}")

    measure_dir = _get_measure_dir()

    # Save current model to temporary OSM
    with tempfile.NamedTemporaryFile(suffix='.osm', delete=False) as temp_file:
        temp_osm_path = temp_file.name

    # CRITICAL: Remove weather file object if present (known issue with view_model measure crash)
    if osm_model.weatherFile().is_initialized():
        logger.info("Temporarily removing weather file object for view_model compatibility.")
        osm_model.weatherFile().get().remove()

    osm_model.save(temp_osm_path, True)

    try:
        # Run the measure
        runner = MeasureRunner()
        result = runner.run(
            model_path=temp_osm_path,
            measure_dir=str(measure_dir),
            arguments={},
            run_simulation=False,
            extra_output_files=["report.html", "run/000_view_model/report.html"]
        )

        # Extract HTML output from extra files
        if "extra_files" not in result or not result["extra_files"]:
            raise RuntimeError("HTML report was not generated by the measure.")

        html_temp_path = None
        for _, path in result["extra_files"].items():
            if path and os.path.exists(path):
                html_temp_path = path
                break

        if not html_temp_path:
            raise RuntimeError("Could not find generated HTML report in output directory.")

        # Move to requested output path
        shutil.copy2(html_temp_path, output_path)

        # Cleanup intermediate HTML
        if os.path.exists(html_temp_path):
            os.unlink(html_temp_path)

        logger.info(f"View Model HTML report generated successfully: {output_path}")
        return output_path

    finally:
        # Clean up temporary OSM files
        if os.path.exists(temp_osm_path):
            os.unlink(temp_osm_path)
        if 'result' in locals() and os.path.exists(result["osm_path"]):
            os.unlink(result["osm_path"])
